sudo: false
dist: xenial
language: python
python:
  - '3.6-dev'
  - '3.6'
  - '3.7'
  - '3.7-dev'
  - '3.8-dev'

notifications:
  email:
    recipients:
      - kostya@yandex.ru
    on_success: never
    on_failure: always

branches:
  only:
    - master

install:
  - pip install -r requirements.txt

script: python manage.py test

deploy:
  provider: pypi
  user: kostya
  password:
    secure: RelbDkMy0ldhUmYTwyOFe/m6MHu4tu4FZJ0T6oI/ubVlwsjAnruVXNyDNdKFcuH5+sZz7g5cJhSvJn/FgLqZKMfE/LfHquaXOPLfDjaNDlytLRt9/8kQs32eWR66GGPJnstGu8kKA2QVI8WJnc8XekWdUjNqW77suUE169O2okGcbaIa9V371XmhzJaLXpUbtzTbMsbO33Ha+FXAsLSSd26pCM1DdDx4IS2xCsrXpmMfo4xK7UfCFqMMVEPynZPhDmm93bfi4KoUf66YIjxDLEnK+7QkSNjfraDgfMrgGGC5La2LjWXNfpJnio+gKe92alr4Pr6RnU4q9kAPTwpRDPRMZon+WJ/Ho+YNl3Co+4mpwJXGjVhcroX3JlmctX1FZk2L0F7ruzeh5fNqsUSMc7neg2FB+LBdgN3HpikixG5NKpqaQX2i5JgYf9Vxq8n09iE89W29SHnTE1DSbTQiycG9X6LJAxhxopyebZe1Tl4A9G1LM0fed1zOd0GIr+SfpZebYBf/rFy80SNXybuu2dBwp0ElKtCjvOKsp61obmIjOavgWcF2FwuegryOEl3/1/6BkQM1SbItmG5fTmee/MGjjL//x/F7DbI4CFCLNJhG3zud8id70/YdWTj1iAFsZEpyyfAa+WX9FzWEQyLKIncEKboD7Xq1ZZmqpboWD98=
  skip_existing: true
  on:
    branch: master
