# Generated by Django 2.2 on 2019-04-06 13:45

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import tasker_account.models
import tasker_account.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Profile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('language', models.CharField(choices=[('en-US', 'English'), ('ru-RU', 'Русский')], default='en', max_length=5, verbose_name='Language')),
                ('gender', models.SmallIntegerField(blank=True, choices=[(1, 'Male'), (2, 'Female')], null=True, verbose_name='Gender')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Birth date')),
                ('phone', models.BigIntegerField(blank=True, null=True, validators=[tasker_account.validators.mobile_number])),
                ('avatar', models.ImageField(blank=True, null=True, upload_to=tasker_account.models.Profile.path)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='User')),
            ],
        ),
    ]
