# Generated by Django 2.2 on 2019-04-06 21:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_account', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='language',
            field=models.CharField(choices=[('af', 'Afrikaans'), ('ar', 'Arabic'), ('ast', 'Asturian'), ('az', 'Azerbaijani'), ('bg', 'Bulgarian'), ('be', 'Belarusian'), ('bn', 'Bengali'), ('br', 'Breton'), ('bs', 'Bosnian'), ('ca', 'Catalan'), ('cs', 'Czech'), ('cy', 'Welsh'), ('da', 'Danish'), ('de', 'German'), ('dsb', 'Lower Sorbian'), ('el', 'Greek'), ('en', 'English'), ('en-au', 'Australian English'), ('en-gb', 'British English'), ('eo', 'Esperanto'), ('es', 'Spanish'), ('es-ar', 'Argentinian Spanish'), ('es-co', 'Colombian Spanish'), ('es-mx', 'Mexican Spanish'), ('es-ni', 'Nicaraguan Spanish'), ('es-ve', 'Venezuelan Spanish'), ('et', 'Estonian'), ('eu', 'Basque'), ('fa', 'Persian'), ('fi', 'Finnish'), ('fr', 'French'), ('fy', 'Frisian'), ('ga', 'Irish'), ('gd', 'Scottish Gaelic'), ('gl', 'Galician'), ('he', 'Hebrew'), ('hi', 'Hindi'), ('hr', 'Croatian'), ('hsb', 'Upper Sorbian'), ('hu', 'Hungarian'), ('hy', 'Armenian'), ('ia', 'Interlingua'), ('id', 'Indonesian'), ('io', 'Ido'), ('is', 'Icelandic'), ('it', 'Italian'), ('ja', 'Japanese'), ('ka', 'Georgian'), ('kab', 'Kabyle'), ('kk', 'Kazakh'), ('km', 'Khmer'), ('kn', 'Kannada'), ('ko', 'Korean'), ('lb', 'Luxembourgish'), ('lt', 'Lithuanian'), ('lv', 'Latvian'), ('mk', 'Macedonian'), ('ml', 'Malayalam'), ('mn', 'Mongolian'), ('mr', 'Marathi'), ('my', 'Burmese'), ('nb', 'Norwegian Bokmål'), ('ne', 'Nepali'), ('nl', 'Dutch'), ('nn', 'Norwegian Nynorsk'), ('os', 'Ossetic'), ('pa', 'Punjabi'), ('pl', 'Polish'), ('pt', 'Portuguese'), ('pt-br', 'Brazilian Portuguese'), ('ro', 'Romanian'), ('ru', 'Russian'), ('sk', 'Slovak'), ('sl', 'Slovenian'), ('sq', 'Albanian'), ('sr', 'Serbian'), ('sr-latn', 'Serbian Latin'), ('sv', 'Swedish'), ('sw', 'Swahili'), ('ta', 'Tamil'), ('te', 'Telugu'), ('th', 'Thai'), ('tr', 'Turkish'), ('tt', 'Tatar'), ('udm', 'Udmurt'), ('uk', 'Ukrainian'), ('ur', 'Urdu'), ('vi', 'Vietnamese'), ('zh-hans', 'Simplified Chinese'), ('zh-hant', 'Traditional Chinese')], default='en', max_length=5, verbose_name='Language'),
        ),
        migrations.CreateModel(
            name='GeobaseTimezone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Time zone')),
            ],
            options={
                'verbose_name': 'Timezone',
                'verbose_name_plural': 'Timezone',
                'unique_together': {('name',)},
            },
        ),
        migrations.CreateModel(
            name='GeobaseProvince',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(db_index=True, max_length=255, verbose_name='Name russian')),
                ('en', models.CharField(db_index=True, max_length=255, verbose_name='Name english')),
            ],
            options={
                'verbose_name': 'Province',
                'verbose_name_plural': 'Province',
                'unique_together': {('ru', 'en')},
            },
        ),
        migrations.CreateModel(
            name='GeobaseLocality',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(db_index=True, max_length=255, verbose_name='Name russian')),
                ('en', models.CharField(db_index=True, max_length=255, verbose_name='Name english')),
            ],
            options={
                'verbose_name': 'Locality',
                'verbose_name_plural': 'Locality',
                'unique_together': {('ru', 'en')},
            },
        ),
        migrations.CreateModel(
            name='GeobaseCountry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ru', models.CharField(db_index=True, max_length=255, verbose_name='Name russian')),
                ('en', models.CharField(db_index=True, max_length=255, verbose_name='Name english')),
            ],
            options={
                'verbose_name': 'Country',
                'verbose_name_plural': 'Country',
                'unique_together': {('ru', 'en')},
            },
        ),
        migrations.CreateModel(
            name='Geobase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('latitude', models.FloatField(verbose_name='Latitude')),
                ('longitude', models.FloatField(verbose_name='Longitude')),
                ('country', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker_account.GeobaseCountry', verbose_name='Country')),
                ('locality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker_account.GeobaseLocality', verbose_name='Locality')),
                ('province', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasker_account.GeobaseProvince', verbose_name='Province')),
                ('timezone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tasker_account.GeobaseTimezone', verbose_name='Time zone')),
            ],
            options={
                'verbose_name': 'Geographical object',
                'verbose_name_plural': 'Geographical objects',
                'unique_together': {('country', 'province', 'locality')},
            },
        ),
    ]
