# Generated by Django 2.2 on 2019-04-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_account', '0002_auto_20190406_2107'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geobasecountry',
            options={'verbose_name': 'Geobase сountry', 'verbose_name_plural': 'Geobase сountry'},
        ),
        migrations.AlterModelOptions(
            name='geobaselocality',
            options={'verbose_name': 'Geobase locality', 'verbose_name_plural': 'Geobase locality'},
        ),
        migrations.AlterModelOptions(
            name='geobaseprovince',
            options={'verbose_name': 'Geobase province', 'verbose_name_plural': 'Geobase province'},
        ),
        migrations.AlterModelOptions(
            name='geobasetimezone',
            options={'verbose_name': 'Geobase timezone', 'verbose_name_plural': 'Geobase timezone'},
        ),
        migrations.AddField(
            model_name='profile',
            name='geobase',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tasker_account.Geobase', verbose_name='Geobase'),
        ),
    ]
