# Generated by Django 2.2 on 2019-04-06 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_account', '0003_auto_20190406_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='geobase',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='tasker_account.Geobase', verbose_name='Geobase'),
        ),
    ]
