# Generated by Django 2.2 on 2019-04-16 03:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tasker_account', '0004_auto_20190406_2114'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='geobase',
            options={'verbose_name': 'Geobase', 'verbose_name_plural': 'Geobase'},
        ),
    ]
