# Generated by Django 2.2 on 2019-05-04 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('django_tasker_account', '0002_oauth'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oauth',
            options={'verbose_name': 'OAuth', 'verbose_name_plural': 'OAuth'},
        ),
        migrations.AlterField(
            model_name='oauth',
            name='refresh_token',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Refresh token'),
        ),
    ]
